# mpv configuration file

# Language preferences
slang=en
alang=en

# Subtitle selection and appearance
sub-auto=all
sub-font="Times New Roman"
sub-color="#FFFFFF00"
sub-shadow-color="#80000000"
sub-shadow-offset=1

# On-screen controller
osc=no

# Playback resume and history
save-position-on-quit=yes
resume-playback=yes
watch-later-options=start
save-watch-history=yes
write-filename-in-watch-later-config=yes

# Screenshot settings
screenshot-directory=~/Pictures/mpv

